<?php

namespace App\Console\Commands;

use App\Enums\Permission;
use App\Enums\RoleName;
use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;

#[Signature('tachi:types {--check : Fail if the generated file is out of date instead of writing it} {--path= : Output file, relative to the project root}')]
#[Description('Generate the TypeScript role and permission constants from the PHP enums')]
class GenerateAccessTypes extends Command
{
    public const DEFAULT_PATH = 'resources/js/constants/access.generated.ts';

    /**
     * Execute the console command.
     */
    public function handle(Filesystem $files): int
    {
        $path = base_path($this->option('path') ?: self::DEFAULT_PATH);
        $contents = $this->render();

        if ($this->option('check')) {
            if (! $files->exists($path) || $files->get($path) !== $contents) {
                $this->components->error('Role and permission types are out of date. Run `php artisan tachi:types`.');

                return self::FAILURE;
            }

            $this->components->info('Role and permission types are up to date.');

            return self::SUCCESS;
        }

        $files->ensureDirectoryExists(dirname($path));
        $files->put($path, $contents);

        $this->components->info("Generated [{$path}].");

        return self::SUCCESS;
    }

    /**
     * Render the TypeScript module.
     */
    public function render(): string
    {
        $roles = collect(RoleName::cases())
            ->map(fn (RoleName $role): string => '    '.Str::upper(Str::snake($role->name)).': '.$this->quote($role->value).',')
            ->implode("\n");

        $permissions = collect(Permission::cases())
            ->map(fn (Permission $permission): string => '    '.Str::upper(Str::snake($permission->name)).': '.$this->quote($permission->value).',')
            ->implode("\n");

        $labels = collect(Permission::cases())
            ->map(fn (Permission $permission): string => '    '.$this->quote($permission->value).': '.$this->quote($permission->label()).',')
            ->implode("\n");

        $groups = collect(Permission::cases())
            ->groupBy(fn (Permission $permission): string => $permission->group())
            ->map(fn ($permissions, string $group): string => '    '.$group.": [\n".$permissions
                ->map(fn (Permission $permission): string => '        '.$this->quote($permission->value).',')
                ->implode("\n")."\n    ],")
            ->implode("\n");

        return <<<TS
        // This file is generated by `php artisan tachi:types` from
        // app/Enums/RoleName.php and app/Enums/Permission.php. Do not edit it.

        export const ROLES = {
        {$roles}
        } as const;

        export type SystemRoleName = (typeof ROLES)[keyof typeof ROLES];

        export const PERMISSIONS = {
        {$permissions}
        } as const;

        export type PermissionName = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

        export const PERMISSION_LABELS: Record<PermissionName, string> = {
        {$labels}
        };

        export const PERMISSION_GROUPS = {
        {$groups}
        } as const satisfies Record<string, readonly PermissionName[]>;

        export type PermissionGroupName = keyof typeof PERMISSION_GROUPS;

        TS;
    }

    /**
     * Quote a value as a single-quoted TypeScript string literal.
     */
    private function quote(string $value): string
    {
        return "'".addcslashes($value, "'\\")."'";
    }
}
