// This file is generated by `php artisan tachi:types` from
// app/Enums/RoleName.php and app/Enums/Permission.php. Do not edit it.

export const ROLES = {
    SUPERADMIN: 'superadmin',
    ADMIN: 'admin',
    USER: 'user',
} as const;

export type SystemRoleName = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
    USERS_VIEW: 'users.view',
    USERS_CREATE: 'users.create',
    USERS_EDIT: 'users.edit',
    USERS_DELETE: 'users.delete',
    USERS_STATUS: 'users.status',
    ROLES_VIEW: 'roles.view',
    ROLES_CREATE: 'roles.create',
    ROLES_EDIT: 'roles.edit',
    ROLES_DELETE: 'roles.delete',
} as const;

export type PermissionName = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_LABELS: Record<PermissionName, string> = {
    'users.view': 'View Users',
    'users.create': 'Create Users',
    'users.edit': 'Edit Users',
    'users.delete': 'Delete Users',
    'users.status': 'Change User Status',
    'roles.view': 'View Roles',
    'roles.create': 'Create Roles',
    'roles.edit': 'Edit Roles',
    'roles.delete': 'Delete Roles',
};

export const PERMISSION_GROUPS = {
    Users: [
        'users.view',
        'users.create',
        'users.edit',
        'users.delete',
        'users.status',
    ],
    Roles: [
        'roles.view',
        'roles.create',
        'roles.edit',
        'roles.delete',
    ],
} as const satisfies Record<string, readonly PermissionName[]>;

export type PermissionGroupName = keyof typeof PERMISSION_GROUPS;
